### ISSUE TITLE
min SDK version too high

### ISSUE THREAD

**Issue by Maatteogekko** [Mehrankhan-METRA-RGB/cross_scroll#2]
Is it necessary to have SDK version >=2.16.0-80.1.beta? The great majority of app will not be able to use this package with a min version that high. Would you consider bringing it down to 2.15?

**Comment by Mehrankhan-METRA-RGB** [comment]
@Maatteogekko  First of all sorry for being late.   I have started working on a couple of issues as it is done, I will solve this issue too. And thanks for letting us know about the issue.

**Comment by Mehrankhan-METRA-RGB** [comment]
The issue has been solved in 0.0.3
