### ISSUE TITLE
Error launching

### ISSUE THREAD

**Issue by Maatteogekko** [Mehrankhan-METRA-RGB/cross_scroll#3]
```
Launching lib/main.dart on Chrome in debug mode...
: Error: The getter 'trackVisibility' isn't defined for the class 'ScrollbarThemeData'.
- 'ScrollbarThemeData' is from 'package:flutter/src/material/scrollbar_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/scrollbar_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'trackVisibility'.
            _scrollbarTheme.trackVisibility?.resolve(states) ??
                            ^^^^^^^^^^^^^^^

: Error: The setter 'ignorePointer' isn't defined for the class 'ScrollbarPainter'.
- 'ScrollbarPainter' is from 'package:flutter/src/widgets/scrollbar.dart' ('../../../flutter/packages/flutter/lib/src/widgets/scrollbar.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'ignorePointer'.
      ..ignorePointer = !enableGestures;
        ^^^^^^^^^^^^^

Failed to compile application.
Exited (sigterm)

```

**Comment by Mehrankhan-METRA-RGB** [comment]
Please provide your **flutter doctor** details. so that I can ensure the real problem because it works perfectly in my case.

Here are my flutter doctor details:

 Flutter (Channel beta, 2.10.0-0.3.pre, on macOS 12.1 21C52 darwin-x64, locale en-PK)
    • Flutter version 2.10.0-0.3.pre at /Users/aaa/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fdd0af78bb (2 weeks ago), 2022-01-25 22:01:33 -0600
    • Engine revision 5ac30ef0c7
    • Dart version 2.16.0 (build 2.16.0-134.5.beta)
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/aaa/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/aaa/Downloads/softs/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by Mehrankhan-METRA-RGB** [comment]
hope you will not see these errors on 0.0.75

**Comment by Maatteogekko** [comment]
Working now on Flutter 2.10. Thank you!
